server:
  port: 8080

spring:
  application:
    name: backend-spring

  datasource:
    # URL kết nối tới Supabase Pooler (chú ý sslmode=require)
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.vhyfauholmouikskxecp
    password: Hungthai@2005
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HueDiMoHikariCP

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # Không tự ý thay đổi cấu trúc bảng sẵn có trên Supabase
    show-sql: true # In câu lệnh SQL ra terminal để dễ học và debug
    properties:
      hibernate:
        format_sql: true # Định dạng SQL đẹp mắt trên console

# Cấu hình JWT (dùng chung secret key với Express để tương thích token)
jwt:
  access-secret: huedimo_jwt_secret_key_secure_hue_travel_2026
  access-expiration: 86400000 # 1 ngày (ms)
  refresh-secret: huedimo_jwt_refresh_secret_key_secure_hue_travel_2026
  refresh-expiration: 2592000000 # 30 ngày (ms)
